# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-11 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 5, 51, 58, 739022))),
                ('started_time', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 5, 51, 58, 739096))),
                ('status', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 5, 51, 58, 740803))),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagecrawl.Crawl')),
            ],
        ),
    ]
