# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecrawl', '0002_auto_20180511_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawl',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
